import type { Metadata } from "next";
import "./globals.css";

import { Didact_Gothic } from "next/font/google";
import { FootBar, NavbarHeader } from "@widgets";
import { headers } from "next/headers";
import { checkAdmin } from "@shared/utils";
import Providers from "providers";
import classNames from "classnames";
import { NextHeaders } from "@shared/consts";
import { NotificationsList } from "@features";

export const didactGothic = Didact_Gothic({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAdmin = checkAdmin(headers());
  const username = headers().get(NextHeaders.XUserName);
  console.log("username - layout", isAdmin, username);
  return (
    <html lang="en">
      <body
        className={classNames(`${didactGothic.className} antialiased`)}
        style={{ colorScheme: "light" }}
      >
        <Providers>
          <NavbarHeader />
          <div
            className="root-layout"
            style={isAdmin ? { marginBottom: "70px" } : {}}
          >
            {children}
          </div>
          {isAdmin && <FootBar />}
          <NotificationsList />
        </Providers>
      </body>
    </html>
  );
}
